image: node:18.17.1

stages:
  - build
  - lint
  - test
  - publish

dependencies:
  stage: build
  script:
    - yarn
    - yarn build
  artifacts:
    paths:
      - node_modules/
      - dist/
    expire_in: 1 week

lint:
  stage: lint
  script:
    - yarn lint

test:
  stage: test
  script:
    - yarn test

publish:
  stage: publish
  before_script:
    - git config --global user.email "bouhelalhamza@gmail.com"
    - git config --global user.name "bouhelalhamza"
  script:
    - yarn release "$CI_COMMIT_MESSAGE"
  only:
    - main
  except:
    - /^no-release.*$/
